# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# CONDITIONS WHICH TRIGGER OR NOT THE JOBS
trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pr:
- master

### GLOBAL VARIABLES ###

variables:

  ## ARTIFACTS CONFIGURATION ##
  nuGetsArtifactName: 'GeoSikNuGets'
  buildArtifactName : 'GeoSikBuild'

  ## GENERAL CONFIGURATION ##
  solution: 'GeoSik.dev.sln'
  vmImage: 'windows-2019'
  artifactDirLocation: $(System.DefaultWorkingDirectory)

  ## NUGET GENERATION ##
  excludeNuGetGeneration: '!$(artifactBuildPath)\**\*.Tests.csproj;!$(artifactBuildPath)\**\Data.Entity.csproj;!$(artifactBuildPath)\**\WebSample.csproj'

  ## NUGET PUBLICATION ##
  nuGetPackagePatternToPublish: $(artifactPath)/**/*.nupkg
  excludeNuGetPackages: '!$(artifactPath)\**\Data.Entity.*.nupkg;!$(artifactPath)\**\WebSample.*.nupkg'
  nuGetFeedCredentials: 'NugetOrg_asIsogeo'
  nuGetSource: https://api.nuget.org/v3/index.json

  ## TEST EXEUCTION ##
  # noBlockingTests: Can't specify false because currently not 100% succeed tests
  # Reason : problem with results of xunit.visualstudio NuGet Package, defer with MSBuild execution tests
  #          in theory, have 100% of succeed tests, but they aren't all full on Azure devops/VisualStudio (compatibility with xunit ?)
  noBlockingTests: 'true'

resources:
  repositories:
    - repository: templates
      type: github
      name: isogeo/devops-templates
      ref: refs/tags/v1.2.0
      endpoint: isogeo

stages:

# See Net/Pipeline/directory for more details about parameters (isogeo/devops-templates repository)
# Mandatory : solution
- template: Net/Pipeline/NuGetsPipelineWithoutPublish.yml@templates
  parameters:
    solution: $(solution)
    nuGetsArtifactName: $(nuGetsArtifactName)
    buildArtifactName : $(buildArtifactName)
    excludeNuGetGeneration: $(excludeNuGetGeneration)
    noBlockingTests: $(noBlockingTests)

- stage: 'Publish'
  jobs:
  - job: 'PublishNuGets'
    pool:
      vmImage: $(vmImage)
    variables:
      artifactPath: $(artifactDirLocation)/$(nuGetsArtifactName)
    steps:
    - template: /Net/Utilities/DownloadNuGetsArtifact.yml@templates
      parameters:
        nugetVersion: 5.1.0
        nuGetsArtifactName: $(nuGetsArtifactName)
        artifactDirLocation: $(System.DefaultWorkingDirectory)
    - script: nuget push $(nuGetPackagePatternToPublish) -Source $(nuGetSource) -ApiKey $(apikey) -SkipDuplicate -NoSymbols
      displayName: 'Publish NuGet packages to www.nuget.org'